# -*- coding: utf-8 -*-
"""Build static seeds for criminal enforcement and prison regulations."""
from __future__ import annotations
import pprint,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];CACHE=ROOT/'data'/'source_cache';OUT=ROOT/'data'/'seed'/'criminal_enforcement.py';F2A=str.maketrans('۰۱۲۳۴۵۶۷۸۹','0123456789');A2F=str.maketrans('0123456789','۰۱۲۳۴۵۶۷۸۹')
def sm(s):
 s=re.sub(r'\[([^]]+)\]\([^)]+\)',r'\1',s);return s.replace('**','').replace('__','').replace('\\-','-').strip()
def clean(s):
 d={'ي':'ی','ك':'ک','ة':'ه','\ufeff':'','\u00ad':'','\u200e':'‌','\u200f':'‌','‎':'‌','‏':'‌','آئین':'آیین','هیات':'هیأت','مسوول':'مسئول','موسسات':'مؤسسات','میباشد':'می‌باشد','میشود':'می‌شود','میشوند':'می‌شوند','میگردد':'می‌گردد','میکند':'می‌کند','میتواند':'می‌تواند','می نماید':'می‌نماید','می شود':'می‌شود','می گردد':'می‌گردد','می باشد':'می‌باشد','نمی باشد':'نمی‌باشد','بموجب':'به موجب','بعهده':'به عهده','بمنظور':'به منظور','بعمل':'به عمل','بکار':'به کار','لازم الاجرا':'لازم‌الاجرا','محکوم علیه':'محکوم‌علیه','محکوم له':'محکوم‌له','حق الزحمه':'حق‌الزحمه','نیمه آزادی':'نیمه‌آزادی','حرفه آموزی':'حرفه‌آموزی','صورت مجلس':'صورت‌جلسه','ذی ربط':'ذی‌ربط','یکبار':'یک بار','ششماه':'شش ماه'}
 for a,b in d.items():s=s.replace(a,b)
 s=re.sub(r'\s*\(\s*(?:اصلاحی|الحاقی|منسوخه?)[^)]*\)\s*[–-]?','',s);s=re.sub(r'‌+','‌',s);s=re.sub(r'[ \t]*‌[ \t]*','‌',s);s=re.sub(r'(^|\n)‌',r'\1',s);s=re.sub(r'([)\]،؛:.])‌',r'\1 ',s);s=re.sub(r'[ \t]+',' ',s);s=re.sub(r' *\n *','\n',s);s=re.sub(r'\n{3,}','\n\n',s);return s.translate(A2F).strip()
def parse(path,wanted):
 a={};cur=None
 for raw in path.read_text().splitlines():
  line=sm(raw);mark=line.lstrip('‌ #').replace('ماده ‌','ماده ').replace('ماده‌','ماده ')
  m=re.match(r'^ماده[\s‌]*(?:\(|（)?([۰-۹0-9]+)(?:\)|）)?(?:[\s‌]*\([^)]*\))?[\s‌]*[ـ–-]?\s*[‌ ]*(.*)$',mark)
  if m:
   n=int(m.group(1).translate(F2A));cur=n if n in wanted and n not in a else None
   if cur:a[cur]=[m.group(2)] if m.group(2) else []
   continue
  if cur is None or not line:continue
  if line.startswith('#') or re.match(r'^(فصل|مبحث|گفتار|بخش)\s',line):continue
  if line.startswith(('این آیین‌نامه مشتمل','این دستورالعمل در','رئیس قوه','معاون اول رئیس جمهور','اسحاق جهانگیری','* * *','انتهای پیام')):cur=None;continue
  if 'https://' in line or '](http' in line:continue
  a[cur].append(line)
 miss=sorted(wanted-set(a))
 if miss:raise ValueError(f'{path.name}: {miss}')
 return {n:clean('\n'.join(a[n])) for n in sorted(wanted)}
def main():
 execution=parse(CACHE/'criminal_procedure_cyber_1393.md',set(range(484,559)))
 judgments=parse(CACHE/'criminal_judgments_bylaw_1398.md',set(range(1,149)))
 prisons=parse(CACHE/'prisons_bylaw_1400.md',set(range(1,343)))
 electronic=parse(CACHE/'electronic_monitoring_bylaw_1397.md',set(range(1,29)))
 alternative=parse(CACHE/'alternative_punishments_bylaw_1393.md',set(range(1,17)))
 directive=parse(CACHE/'prison_population_directive_1398.md',set(range(1,30)))
 limits=parse(CACHE/'electronic_monitoring_limits_1401.md',set(range(1,5)))
 vals={'CRIMINAL_EXECUTION_SECTION':tuple(execution.items()),'CRIMINAL_JUDGMENTS_BYLAW':tuple(judgments.items()),'PRISONS_BYLAW':tuple(prisons.items()),'ELECTRONIC_MONITORING_BYLAW':tuple(electronic.items()),'ALTERNATIVE_PUNISHMENTS_BYLAW':tuple(alternative.items()),'PRISON_POPULATION_DIRECTIVE':tuple(directive.items()),'ELECTRONIC_LIMITS_DIRECTIVE':tuple(limits.items())}
 head='# -*- coding: utf-8 -*-\n"""Generated static texts for criminal enforcement and prison regulations."""\n# Generated by scripts/build_criminal_enforcement_seeds.py.\n\n';OUT.write_text(head+''.join(f'{k} = {pprint.pformat(v,width=120,sort_dicts=False)}\n\n' for k,v in vals.items()))
 print(f'[OK] execution={len(execution)}; judgments={len(judgments)}; prisons={len(prisons)}; electronic={len(electronic)}; alternatives={len(alternative)}; population={len(directive)}; limits={len(limits)}')
 print(f'[OK] wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size:,} bytes)')
if __name__=='__main__':main()
