#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Load the category folders uploaded under ``iran_legal_db/data``.

The loader owns stable ``UPL-*`` reference codes generated by
``build_uploaded_data_seeds.py``.  It is transactional and idempotent: rerunning
it replaces only rows owned by those uploaded documents and never duplicates or
removes data from the established legal packages.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / "scripts"), str(ROOT / "data" / "seed")]

from importer import add_article, add_tag, get_or_create_document, link_document_tag, link_document_topic  # noqa: E402
from schema import get_connection  # noqa: E402
from uploaded_data import DOCUMENTS  # noqa: E402


JUDICIAL_AUTHORITIES = {
    "قوه قضائیه",
    "رئیس قوه قضائیه",
    "مرجع داوری مندرج در منبع",
}
EXECUTIVE_AUTHORITIES = {
    "وزارت آموزش و پرورش",
    "وزارت دادگستری",
    "وزارت امور خارجه",
    "سازمان ثبت اسناد و املاک کشور",
    "وزارت راه و شهرسازی",
    "وزارت کشور",
    "وزارت امور اقتصادی و دارایی",
    "سازمان حفاظت محیط زیست",
    "وزارت دفاع و پشتیبانی نیروهای مسلح",
    "وزارت ورزش و جوانان",
    "بنیاد شهید و امور ایثارگران",
    "هیئت وزیران",
}


def one(conn, sql: str, value: str):
    row = conn.execute(sql, (value,)).fetchone()
    return row["id"] if row else None


def ensure_authority(conn, name: str) -> int:
    row = conn.execute("SELECT id FROM authorities WHERE name_fa=?", (name,)).fetchone()
    if row:
        return row["id"]
    if name in JUDICIAL_AUTHORITIES:
        kind = "judicial"
    elif name in EXECUTIVE_AUTHORITIES:
        kind = "executive"
    else:
        kind = "legislative"
    cur = conn.execute("INSERT INTO authorities(name_fa, authority_type) VALUES(?, ?)", (name, kind))
    return cur.lastrowid


def upsert_document(conn, doc: dict) -> int:
    authority_id = ensure_authority(conn, doc["authority"])
    did = one(conn, "SELECT id FROM documents WHERE reference_code=?", doc["ref"])
    if not did:
        did = get_or_create_document(
            conn,
            title=doc["title"],
            short_title=doc["short"],
            type_code=doc["type_code"],
            issuing_authority=doc["authority"],
            status_code=doc["status_code"],
            ratification_date=doc["date"],
            effective_date=doc["date"],
            reference_code=doc["ref"],
            notes=doc["notes"],
        )
    conn.execute(
        """
        UPDATE documents
        SET title=?, short_title=?, type_id=?, issuing_authority_id=?, status_id=?,
            ratification_date=?, effective_date=?, notes=?
        WHERE id=?
        """,
        (
            doc["title"],
            doc["short"],
            one(conn, "SELECT id FROM document_types WHERE code=?", doc["type_code"]),
            authority_id,
            one(conn, "SELECT id FROM statuses WHERE code=?", doc["status_code"]),
            doc["date"],
            doc["date"],
            doc["notes"],
            did,
        ),
    )
    return did


def clear_owned(conn, document_id: int) -> None:
    for sql in (
        "DELETE FROM relations WHERE from_document_id=?",
        "DELETE FROM articles_fts WHERE document_id=?",
        "DELETE FROM articles WHERE document_id=?",
        "DELETE FROM document_tags WHERE document_id=?",
        "DELETE FROM document_topics WHERE document_id=?",
    ):
        conn.execute(sql, (document_id,))


def attach_labels(conn, document_id: int, doc: dict) -> None:
    conn.execute("INSERT OR IGNORE INTO topics(name_fa) VALUES(?)", (doc["topic"],))
    link_document_topic(conn, document_id, doc["topic"])
    # Keep a category tag as well as a few searchable subject tags.  The raw
    # category is deliberately preserved so future curation can filter the pack.
    tags = {f"آپلود: {doc['category']}", doc["topic"]}
    title = doc["title"]
    for word in (
        "آموزش", "مدرسه", "دانشگاه", "ایثارگر", "زمین", "ملک", "ثبت", "وکالت", "خانواده",
        "داوری", "شهرداری", "مالیات", "بودجه", "محیط زیست", "مسکن", "نظامی", "ورزش",
        "فوتبال", "حمل و نقل", "معاهده", "پزشکی", "کشاورزی", "شرکت",
    ):
        if word in title:
            tags.add(word)
    for tag in sorted(tags):
        link_document_tag(conn, document_id, add_tag(conn, tag))


def add_rows(conn, document_id: int, doc: dict) -> None:
    historical = doc["status_code"] == "abrogated"
    for row in doc["rows"]:
        source = "؛ ".join(doc["source_urls"]) if doc["source_urls"] else "منبع URL در فایل خام درج نشده است"
        source += "؛ فایل خام: " + ", ".join(doc["source_paths"])
        add_article(
            conn,
            document_id,
            article_no=row["article_no"],
            article_key=f"{doc['ref']}:{row['article_key_suffix']}",
            version_no=1,
            is_current=0 if historical else 1,
            effective_date=doc["date"],
            expiry_date=doc["date"] if historical else None,
            text=row["text"],
            source_note=source,
            notes="استخراج خودکار از داده TXT آپلودشده؛ متن رسمی و وضعیت تنقیحی باید مقابله شود.",
        )


def load_document(conn, doc: dict) -> None:
    did = upsert_document(conn, doc)
    clear_owned(conn, did)
    attach_labels(conn, did, doc)
    add_rows(conn, did, doc)


def main() -> None:
    conn = get_connection()
    try:
        conn.execute("BEGIN")
        for doc in DOCUMENTS:
            load_document(conn, doc)
        conn.commit()
        total = sum(doc["article_count"] for doc in DOCUMENTS)
        print(f"loaded uploaded data: {len(DOCUMENTS)} documents / {total} articles")
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


if __name__ == "__main__":
    main()
